import json
from typing import Optional

from config.config import GDMADSettings

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None  # OpenAI SDK is optional when using mock mode


class LLMClient:
    def __init__(self, settings: GDMADSettings):
        self.settings = settings
        self.use_mock = self.settings.use_mock_llm
        self.api_key = self.settings.api_key
        self.model_name = self.settings.model_name
        self.client = None
        self.enabled = False

        if self.use_mock:
            self.enabled = True
            return

        if self.api_key and OpenAI is not None:
            self.client = OpenAI(
                api_key=self.api_key,
                base_url=self.settings.api_base if self.settings.api_base else None,
            )
            self.enabled = True

    def generate(self, prompt: str, temperature: Optional[float] = None, max_tokens: Optional[int] = None) -> str:
        if not self.enabled:
            return "No API key found and mock LLM is disabled. Set USE_MOCK_LLM=true or provide an API key."

        if self.use_mock:
            return self._mock_generate(prompt)

        params = {
            "model": self.model_name,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": temperature if temperature is not None else self.settings.temperature,
            "max_tokens": max_tokens if max_tokens is not None else self.settings.max_tokens,
        }

        response = self.client.chat.completions.create(**params)
        return response.choices[0].message.content.strip()

    def _mock_generate(self, prompt: str) -> str:
        if "Group answers" in prompt or "Group answers:" in prompt:
            group_count = max(1, prompt.count("Group ") // 2)
            groups = [
                {
                    "Group_Index": idx + 1,
                    "Evidence_Grounding": 5,
                    "Logical_Coherence": 5,
                    "Hallucination_Detection": 5,
                    "Depth_of_Thought": 5,
                    "Detailed_Reasoning": "Mock evaluation generated by the mock LLM.",
                    "Total_Score": 5,
                }
                for idx in range(group_count)
            ]
            return json.dumps(groups)

        if "Final answer:" in prompt or "Provide a final answer" in prompt or "Final answer" in prompt:
            return "Mock answer: This is a placeholder response generated by the mock LLM."

        return "Mock answer: " + prompt.strip().replace("\n", " ")[:250]

